ARTWORKS = [
    {
        "id": 1,
        "title": "Digital Sunset",
        "artist": "Alex Turner",
        "price": 550,
        "image": "https://placehold.co/900x600/228B22/FFFFFF?text=Digital+Sunset",
        "category": "Digital Art",
        "medium": "Digital Print",
        "dimensions": "80 x 120 cm",
        "description": "A vivid contemporary sunset composition with layered greens and warm tonal contrast.",
        "featured": True,
    },
    {
        "id": 2,
        "title": "The Iron Muse",
        "artist": "Maria Rodriguez",
        "price": 12000,
        "image": "https://placehold.co/900x600/8B4513/FFFFFF?text=The+Iron+Muse",
        "category": "Sculpture",
        "medium": "Mixed Metal",
        "dimensions": "150 x 60 cm",
        "description": "An industrial sculpture balancing strength, elegance, and contemporary gallery presence.",
        "featured": True,
    },
    {
        "id": 3,
        "title": "A Quiet Day",
        "artist": "John Smith",
        "price": 1500,
        "image": "https://placehold.co/900x600/1E90FF/FFFFFF?text=A+Quiet+Day",
        "category": "Painting",
        "medium": "Oil on Canvas",
        "dimensions": "60 x 90 cm",
        "description": "A calm visual study designed to soften interiors and create a contemplative mood.",
        "featured": False,
    },
    {
        "id": 4,
        "title": "Neon Dreams",
        "artist": "Sarah Chen",
        "price": 850,
        "image": "https://placehold.co/900x600/FF00FF/FFFFFF?text=Neon+Dreams",
        "category": "Digital Art",
        "medium": "Light-Based Print",
        "dimensions": "70 x 100 cm",
        "description": "A vibrant nightlife-inspired work with strong color energy and futuristic tone.",
        "featured": True,
    },
    {
        "id": 5,
        "title": "Marble Echo",
        "artist": "David Stone",
        "price": 4200,
        "image": "https://placehold.co/900x600/708090/FFFFFF?text=Marble+Echo",
        "category": "Sculpture",
        "medium": "Marble Composite",
        "dimensions": "90 x 40 cm",
        "description": "A sculptural piece with texture-forward elegance suited for collectors and modern interiors.",
        "featured": False,
    },
    {
        "id": 6,
        "title": "Fragmented Soul",
        "artist": "Elena Rossi",
        "price": 3100,
        "image": "https://placehold.co/900x600/4B0082/FFFFFF?text=Fragmented+Soul",
        "category": "Abstract",
        "medium": "Acrylic on Canvas",
        "dimensions": "100 x 100 cm",
        "description": "A layered abstract work focused on movement, emotion, and fragmented identity.",
        "featured": True,
    },
]
